name = "Inti"
uuid = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ElementaryPDESolutions = "88a69b33-da0f-4502-8c8c-d680cf4d883b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
FMM2D = "2d63477d-9690-4b75-bcc1-c3461d43fecc"
FMM3D = "1e13804c-f9b7-11ea-0ef0-29f3b1745df8"
FMMLIB2D = "1a804d9e-d798-534b-a6a9-4525c36f0718"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
HMatrices = "8646bddf-ab1c-4fa7-9c51-ba187d647618"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[extensions]
IntiFMM2DExt = "FMM2D"
IntiFMM3DExt = "FMM3D"
IntiFMMLIB2DExt = "FMMLIB2D"
IntiGmshExt = "Gmsh"
IntiHMatricesExt = "HMatrices"
IntiMeshesExt = "Meshes"

[compat]
DataStructures = "0.18"
ElementaryPDESolutions = "0.2"
FMM2D = "0.2"
FMM3D = "1"
FMMLIB2D = "0.3"
ForwardDiff = "0.10"
Gmsh = "0.3"
HMatrices = "0.2"
LinearAlgebra = "1"
LinearMaps = "3"
Meshes = "0.42, 0.43, 0.44"
NearestNeighbors = "0.4"
Printf = "1"
SparseArrays = "1"
SpecialFunctions = "2"
StaticArrays = "1"
julia = "1.6"
