name = "Inti"
uuid = "fb74042b-437e-4c5b-88cf-d4e2beb394d5"
version = "0.1.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
ElementaryPDESolutions = "88a69b33-da0f-4502-8c8c-d680cf4d883b"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearMaps = "7a12625a-238d-50fd-b39a-03d52299707e"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[weakdeps]
FMM2D = "2d63477d-9690-4b75-bcc1-c3461d43fecc"
FMM3D = "1e13804c-f9b7-11ea-0ef0-29f3b1745df8"
FMMLIB2D = "1a804d9e-d798-534b-a6a9-4525c36f0718"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
HMatrices = "8646bddf-ab1c-4fa7-9c51-ba187d647618"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"

[extensions]
IntiFMM2DExt = "FMM2D"
IntiFMM3DExt = "FMM3D"
IntiFMMLIB2DExt = "FMMLIB2D"
IntiGmshExt = "Gmsh"
IntiHMatricesExt = "HMatrices"
IntiMakieExt = ["Meshes", "Makie"]

[compat]
DataStructures = "0.18"
ElementaryPDESolutions = "0.2"
FMM2D = "0.2"
FMM3D = "1"
FMMLIB2D = "0.3"
ForwardDiff = "0.10"
Gmsh = "0.3"
HMatrices = "0.2"
LinearAlgebra = "1"
LinearMaps = "3"
Makie = "0.21"
Meshes = "0.42, 0.43, 0.44, 0.45, 0.46, 0.49"
NearestNeighbors = "0.4"
Pkg = "1"
Printf = "1"
Scratch = "1"
SparseArrays = "1"
SpecialFunctions = "2"
StaticArrays = "1"
TOML = "1"
julia = "1.9"
